print("*****Task 5-User Inputs, Other Important Datatypes*****")
print("Excercise")
print("1.Write a program to create a list of n integer values and do the following:\na.Add an item in to the list (using function)\nb.Delete (using function)\nc.Store the largest number from the list to a variabled\nd.Store the Smallest number from the list to a variable")
print("\n")
lst=list(range(0,10))
print("list=",lst)
print("List after adding an item")
lst.append(10)
print(lst)
print("list after removing an item")
del lst[0]
print(lst)
print("Largest and smallest number in the list")
print("Largest number:",max(lst))
print("Smallest number:",min(lst))
print("\n")
print("2.Create a tuple and print the reverse of the created tuple")
tup=(10,20,30,40,50)
print("Tuple=",tup)
reverse=tup[::-1]
print("tuple after reversing:",reverse)
print("\n")
print("3.Create a tuple and convert tuple into list")
tup1=(5,10,15,20,25,30)
print("Tuple=",tup1)
print("Tuple after converting into list")
lst=list(tup1)
print("List elements:",lst)
print("\n")
print("---------Task 5 Completed---------")